# Generated by Django 4.2.1 on 2023-05-16 01:43

from django.db import migrations

from animals.models import Animal


def create_initial_animals(apps, schema_editor):
    animals = [
        Animal(species="cat", name="Jasper",age=1),
        Animal(species="dog", name="Gertrude",age=3),
        Animal(species="dog", name="Abe",age=6),
        Animal(species="cat", name="Abbott",age=3),
        Animal(species="cat", name="Ace",age=22),
        Animal(species="dog", name="Aero",age=20),
        Animal(species="dog", name="Aiden",age=13),
        Animal(species="dog", name="AJ",age=23),
        Animal(species="cat", name="Albert",age=1),
        Animal(species="dog", name="Alden",age=4),
        Animal(species="dog", name="Bentley",age=22),
        Animal(species="cat", name="Alfie",age=3),
        Animal(species="cat", name="Alvin",age=0),
        Animal(species="cat", name="Amos",age=4),
        Animal(species="dog", name="Andy",age=9),
        Animal(species="cat", name="Angus",age=7),
        Animal(species="dog", name="Apollo",age=12),
        Animal(species="dog", name="Archie",age=18),
        Animal(species="cat", name="AJ",age=22),
        Animal(species="cat", name="Artie",age=18),
        Animal(species="dog", name="Ash",age=23),
        Animal(species="dog", name="Austin",age=18),
        Animal(species="dog", name="Abe",age=7),
        Animal(species="cat", name="Bailey",age=9),
        Animal(species="dog", name="Baxter",age=8),
        Animal(species="dog", name="Abe",age=6),
        Animal(species="cat", name="Bentley",age=5),
        Animal(species="cat", name="Bentley",age=16),
        Animal(species="cat", name="Baxter",age=19),
        Animal(species="dog", name="Alyssa",age=7),
        Animal(species="cat", name="Beau",age=16),
        Animal(species="dog", name="Benji",age=17),
        Animal(species="dog", name="Benny",age=16),
        Animal(species="cat", name="Bentley",age=17),
        Animal(species="cat", name="Billy",age=5),
        Animal(species="dog", name="Cassie",age=16),
        Animal(species="dog", name="Blake",age=20),
        Animal(species="dog", name="Blaze",age=10),
        Animal(species="cat", name="Alyssa",age=7),
        Animal(species="dog", name="Bo",age=3),
        Animal(species="dog", name="Boomer",age=21),
        Animal(species="cat", name="Brady",age=2),
        Animal(species="dog", name="Brody",age=21),
        Animal(species="dog", name="Brownie",age=23),
        Animal(species="cat", name="Bruce",age=21),
        Animal(species="cat", name="Bruno",age=11),
        Animal(species="dog", name="Brutus",age=0),
        Animal(species="dog", name="Abby",age=3),
        Animal(species="dog", name="Addie",age=5),
        Animal(species="cat", name="Alexis",age=16),
        Animal(species="dog", name="Alice",age=19),
        Animal(species="dog", name="Allie",age=12),
        Animal(species="cat", name="Alyssa",age=18),
        Animal(species="cat", name="Amber",age=5),
        Animal(species="cat", name="Angel",age=21),
        Animal(species="dog", name="Anna",age=19),
        Animal(species="dog", name="Annie",age=2),
        Animal(species="cat", name="Ariel",age=19),
        Animal(species="cat", name="Ashley",age=1),
        Animal(species="dog", name="Aspen",age=6),
        Animal(species="dog", name="Athena",age=18),
        Animal(species="dog", name="Autumn",age=12),
        Animal(species="cat", name="Cassie",age=17),
        Animal(species="dog", name="Avery",age=5),
        Animal(species="dog", name="Baby",age=16),
        Animal(species="cat", name="Bailey",age=17),
        Animal(species="cat", name="Basil",age=0),
        Animal(species="cat", name="Bean",age=10),
        Animal(species="dog", name="Bella",age=17),
        Animal(species="cat", name="Belle",age=5),
        Animal(species="dog", name="Betsy",age=20),
        Animal(species="dog", name="Betty",age=10),
        Animal(species="cat", name="Bianca",age=0),
        Animal(species="cat", name="Birdie",age=19),
        Animal(species="dog", name="Biscuit",age=2),
        Animal(species="dog", name="Blondie",age=1),
        Animal(species="cat", name="Blossom",age=9),
        Animal(species="dog", name="Cassie",age=16),
        Animal(species="dog", name="Bella",age=20),
        Animal(species="cat", name="Brooklyn",age=13),
        Animal(species="cat", name="Brownie",age=3),
        Animal(species="dog", name="Buffy",age=2),
        Animal(species="dog", name="Callie",age=18),
        Animal(species="dog", name="Camilla",age=4),
        Animal(species="cat", name="Cassie",age=5),
        Animal(species="dog", name="Bella",age=10),
        Animal(species="dog", name="Carly",age=19),
        Animal(species="cat", name="Carmela",age=16),
        Animal(species="cat", name="Casey",age=10),
        Animal(species="cat", name="Cassie",age=19),
        Animal(species="dog", name="Chance",age=8),
        Animal(species="cat", name="Chanel",age=8),
    ]

    Animal.objects.bulk_create(
        animals
    )

        
class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_animals)
    ]

