# Generated by Django 4.2.1 on 2023-05-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20230516_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bunny', 'Bunny')], max_length=100),
        ),
    ]
